<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>


        <div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>Company Logo</b>
 &nbsp;&nbsp;&nbsp;
        
    
            <a href="<?php echo $this->url(
                array(
                    'controller' => 'album',
                    'action'     => 'add'
                ),
                'default',
                true) ?>">Add Album</a>
  &nbsp;&nbsp;&nbsp;
            <a href="<?php echo $this->url(
                array(
                    'controller' => 'album',
                    'action'     => 'index'
                ),
                'default',
                true) ?>">Show Albums</a>
 &nbsp;&nbsp;&nbsp;
            <a href="<?php echo $this->url(
                array(
                    'controller' => 'index',
                    'action'     => 'add'
                ),
                'default',
                true) ?>">Register</a>
  
</div>
   


  <div id="header-navigation" style="float: right">
      <?php  if(Zend_Auth::getInstance()->hasIdentity()){
    $user = Zend_Auth::getInstance();
    $userName= $user->getIdentity()->fname;
    echo 'Welcome to ' . $userName;
}
?>
      &nbsp;&nbsp;&nbsp;
        <?php if(!Zend_Auth::getInstance()->hasIdentity()){ ?>
        
            <a href="<?php echo $this->url(
                array(
                    'controller' => 'login',
                    'action'     => 'index'
                ),
                'default',
                true) ?>"> Login</a>
        
        <?php } ?>
<?php if(Zend_Auth::getInstance()->hasIdentity()){ ?>
        

            <a href="<?php echo $this->url(
                array(
                    'controller' => 'login',
                    'action'     => 'logout'
                ),
                'default',
                true) ?>">Logout</a>
        
        <?php } ?>
    </div>
</div>

<?php echo $this->layout()->content ?>
    </body>
</html>

